language: node_js
node_js:
- '11'
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'klis'
- git config --global user.email qiang.liao@outlook.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
