language: node_js
node_js:
- '11'
branches:
  only:
  - hexo
before_install:
- git config --global user.name "klis"
- git config --global user.email "qiang.liao@outlook.com"
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$REPO_TOKEN@github.com/hapihapidoge/hapihapidoge.github.io.git master
